// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSheets(arg1) {
  return window['go']['main']['App']['GetSheets'](arg1);
}

export function OpenFileLocation(arg1) {
  return window['go']['main']['App']['OpenFileLocation'](arg1);
}

export function Process(arg1) {
  return window['go']['main']['App']['Process'](arg1);
}

export function SelectExcelFile() {
  return window['go']['main']['App']['SelectExcelFile']();
}

export function SelectImageFolder() {
  return window['go']['main']['App']['SelectImageFolder']();
}
