// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSheets(arg1:string):Promise<Array<string>>;

export function OpenFileLocation(arg1:string):Promise<void>;

export function Process(arg1:main.Config):Promise<main.ProcessResult>;

export function SelectExcelFile():Promise<string>;

export function SelectImageFolder():Promise<string>;
